In [6]:
import pandas as pd

In [17]:
import pandas as pd

df = pd.read_csv(r"C:\Users\ASUS\Downloads\puma.csv")

In [18]:
df.shape

(100000, 16)

In [19]:
df

,order_id,customer_id,product,category,price,quantity,discount_percent,total_amount,city,region,store,sales_channel,size,payment_method,order_date,rating
0,1.0,1049.0,Cap,Accessories,1767.0,4.0,22.0,5513.04,Pune,West,Puma Store B,Online,XL,Card,2023-01-28,3.0
1,2.0,1142.0,Running Shoes,NaN,7122.0,3.0,26.0,15810.84,Mumbai,North,Puma Store C,NaN,S,Cash,2023-11-30,1.0
2,3.0,4121.0,Jacket,Apparel,2464.0,1.0,29.0,1749.44,Mumbai,South,Puma Store B,NaN,S,Card,2023-11-30,2.0
3,4.0,2920.0,NaN,Accessories,912.0,4.0,26.0,2699.52,Hyderabad,North,Puma Store C,NaN,S,Cash,NaN,3.0
4,NaN,1429.0,NaN,Apparel,3741.0,3.0,28.0,NaN,NaN,South,Puma Store C,Online,S,Cash,2023-11-29,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,NaN,1582.0,Cap,Accessories,NaN,2.0,NaN,1794.50,Mumbai,South,Puma Store A,Store,XL,UPI,2023-07-07,1.0
99996,99997.0,3208.0,Cap,Accessories,1616.0,1.0,NaN,1228.16,Mumbai,West,Puma Store C,Store,M,Card,2023-11-10,1.0
99997,99998.0,NaN,Shorts,Apparel,4115.0,4.0,27.0,12015.80,Bangalore,North,Puma Store A,Online,M,UPI,2023-06-08,2.0
99998,99999.0,1047.0,NaN,Footwear,7134.0,1.0,25.0,5350.50,Hyderabad,North,Puma Store B,Online,XL,UPI,2023-08-29,5.0
99999,100000.0,2716.0,T-shirt,Apparel,4683.0,2.0,6.0,8804.04,Pune,West,Puma Store C,Store,S,Card,2023-06-15,2.0

In [20]:
df.head()

,order_id,customer_id,product,category,price,quantity,discount_percent,total_amount,city,region,store,sales_channel,size,payment_method,order_date,rating
0,1.0,1049.0,Cap,Accessories,1767.0,4.0,22.0,5513.04,Pune,West,Puma Store B,Online,XL,Card,2023-01-28,3.0
1,2.0,1142.0,Running Shoes,NaN,7122.0,3.0,26.0,15810.84,Mumbai,North,Puma Store C,NaN,S,Cash,2023-11-30,1.0
2,3.0,4121.0,Jacket,Apparel,2464.0,1.0,29.0,1749.44,Mumbai,South,Puma Store B,NaN,S,Card,2023-11-30,2.0
3,4.0,2920.0,NaN,Accessories,912.0,4.0,26.0,2699.52,Hyderabad,North,Puma Store C,NaN,S,Cash,NaN,3.0
4,NaN,1429.0,NaN,Apparel,3741.0,3.0,28.0,NaN,NaN,South,Puma Store C,Online,S,Cash,2023-11-29,2.0

In [21]:
df.isnull().sum().sum()

np.int64(160000)

In [24]:
df.shape

(100000, 16)

In [25]:
df.isnull().sum()

order_id            10000
customer_id         10000
product             10000
category            10000
price               10000
quantity            10000
discount_percent    10000
total_amount        10000
city                10000
region              10000
store               10000
sales_channel       10000
size                10000
payment_method      10000
order_date          10000
rating              10000
dtype: int64

In [27]:
df.dtypes

order_id            float64
customer_id         float64
product                 str
category                str
price               float64
quantity            float64
discount_percent    float64
total_amount        float64
city                    str
region                  str
store                   str
sales_channel           str
size                    str
payment_method          str
order_date              str
rating              float64
dtype: object

In [28]:
df["order_id"] = df["order_id"].astype("Int64")
df["customer_id"] = df["customer_id"].astype("Int64")

In [29]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

In [30]:
df.dtypes

order_id                     Int64
customer_id                  Int64
product                        str
category                       str
price                      float64
quantity                   float64
discount_percent           float64
total_amount               float64
city                           str
region                         str
store                          str
sales_channel                  str
size                           str
payment_method                 str
order_date          datetime64[us]
rating                     float64
dtype: object

In [31]:
df = df[(df["price"] >= 0) & (df["quantity"] >= 0) & (df["total_amount"] >= 0)]

In [32]:
text_cols = ["product","category","city","region","store",
             "sales_channel","size","payment_method"]

for c in text_cols:
    df[c] = df[c].str.strip()

In [33]:
df

,order_id,customer_id,product,category,price,quantity,discount_percent,total_amount,city,region,store,sales_channel,size,payment_method,order_date,rating
0,1,1049,Cap,Accessories,1767.0,4.0,22.0,5513.04,Pune,West,Puma Store B,Online,XL,Card,2023-01-28,3.0
1,2,1142,Running Shoes,NaN,7122.0,3.0,26.0,15810.84,Mumbai,North,Puma Store C,NaN,S,Cash,2023-11-30,1.0
2,3,4121,Jacket,Apparel,2464.0,1.0,29.0,1749.44,Mumbai,South,Puma Store B,NaN,S,Card,2023-11-30,2.0
3,4,2920,NaN,Accessories,912.0,4.0,26.0,2699.52,Hyderabad,North,Puma Store C,NaN,S,Cash,NaT,3.0
5,6,3511,Jacket,Apparel,1107.0,1.0,13.0,963.09,Pune,South,Puma Store A,Store,S,UPI,2023-09-22,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,99995,3986,Sneakers,Footwear,5097.0,4.0,NaN,15902.64,Bangalore,North,Puma Store C,Online,L,Cash,2023-11-12,4.0
99996,99997,3208,Cap,Accessories,1616.0,1.0,NaN,1228.16,Mumbai,West,Puma Store C,Store,M,Card,2023-11-10,1.0
99997,99998,<NA>,Shorts,Apparel,4115.0,4.0,27.0,12015.80,Bangalore,North,Puma Store A,Online,M,UPI,2023-06-08,2.0
99998,99999,1047,NaN,Footwear,7134.0,1.0,25.0,5350.50,Hyderabad,North,Puma Store B,Online,XL,UPI,2023-08-29,5.0
99999,100000,2716,T-shirt,Apparel,4683.0,2.0,6.0,8804.04,Pune,West,Puma Store C,Store,S,Card,2023-06-15,2.0

In [35]:
num_cols = df.select_dtypes(include="number").columns


num_cols = [c for c in num_cols if c not in ["order_id","customer_id"]]

df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [36]:
df

,order_id,customer_id,product,category,price,quantity,discount_percent,total_amount,city,region,store,sales_channel,size,payment_method,order_date,rating
0,1,1049,Cap,Accessories,1767.0,4.0,22.0,5513.04,Pune,West,Puma Store B,Online,XL,Card,2023-01-28,3.0
1,2,1142,Running Shoes,NaN,7122.0,3.0,26.0,15810.84,Mumbai,North,Puma Store C,NaN,S,Cash,2023-11-30,1.0
2,3,4121,Jacket,Apparel,2464.0,1.0,29.0,1749.44,Mumbai,South,Puma Store B,NaN,S,Card,2023-11-30,2.0
3,4,2920,NaN,Accessories,912.0,4.0,26.0,2699.52,Hyderabad,North,Puma Store C,NaN,S,Cash,NaT,3.0
5,6,3511,Jacket,Apparel,1107.0,1.0,13.0,963.09,Pune,South,Puma Store A,Store,S,UPI,2023-09-22,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,99995,3986,Sneakers,Footwear,5097.0,4.0,15.0,15902.64,Bangalore,North,Puma Store C,Online,L,Cash,2023-11-12,4.0
99996,99997,3208,Cap,Accessories,1616.0,1.0,15.0,1228.16,Mumbai,West,Puma Store C,Store,M,Card,2023-11-10,1.0
99997,99998,<NA>,Shorts,Apparel,4115.0,4.0,27.0,12015.80,Bangalore,North,Puma Store A,Online,M,UPI,2023-06-08,2.0
99998,99999,1047,NaN,Footwear,7134.0,1.0,25.0,5350.50,Hyderabad,North,Puma Store B,Online,XL,UPI,2023-08-29,5.0
99999,100000,2716,T-shirt,Apparel,4683.0,2.0,6.0,8804.04,Pune,West,Puma Store C,Store,S,Card,2023-06-15,2.0

In [37]:
cat_cols = df.select_dtypes(include="object").columns
df[cat_cols] = df[cat_cols].fillna("Unknown")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_13664\2478693583.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include="object").columns

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.drop_duplicates()

,order_id,customer_id,product,category,price,quantity,discount_percent,total_amount,city,region,store,sales_channel,size,payment_method,order_date,rating
0,1,1049,Cap,Accessories,1767.0,4.0,22.0,5513.04,Pune,West,Puma Store B,Online,XL,Card,2023-01-28,3.0
1,2,1142,Running Shoes,Unknown,7122.0,3.0,26.0,15810.84,Mumbai,North,Puma Store C,Unknown,S,Cash,2023-11-30,1.0
2,3,4121,Jacket,Apparel,2464.0,1.0,29.0,1749.44,Mumbai,South,Puma Store B,Unknown,S,Card,2023-11-30,2.0
3,4,2920,Unknown,Accessories,912.0,4.0,26.0,2699.52,Hyderabad,North,Puma Store C,Unknown,S,Cash,NaT,3.0
5,6,3511,Jacket,Apparel,1107.0,1.0,13.0,963.09,Pune,South,Puma Store A,Store,S,UPI,2023-09-22,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,99995,3986,Sneakers,Footwear,5097.0,4.0,15.0,15902.64,Bangalore,North,Puma Store C,Online,L,Cash,2023-11-12,4.0
99996,99997,3208,Cap,Accessories,1616.0,1.0,15.0,1228.16,Mumbai,West,Puma Store C,Store,M,Card,2023-11-10,1.0
99997,99998,<NA>,Shorts,Apparel,4115.0,4.0,27.0,12015.80,Bangalore,North,Puma Store A,Online,M,UPI,2023-06-08,2.0
99998,99999,1047,Unknown,Footwear,7134.0,1.0,25.0,5350.50,Hyderabad,North,Puma Store B,Online,XL,UPI,2023-08-29,5.0
99999,100000,2716,T-shirt,Apparel,4683.0,2.0,6.0,8804.04,Pune,West,Puma Store C,Store,S,Card,2023-06-15,2.0

In [41]:
df = df[df["price"] >= 0]
df = df[df["quantity"] >= 0]

In [42]:
df[df["rating"] > 5]
df["rating"] = df["rating"].clip(0, 5)

In [43]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

In [44]:
df

,order_id,customer_id,product,category,price,quantity,discount_percent,total_amount,city,region,store,sales_channel,size,payment_method,order_date,rating
0,1,1049,Cap,Accessories,1767.0,4.0,22.0,5513.04,Pune,West,Puma Store B,Online,XL,Card,2023-01-28,3.0
1,2,1142,Running Shoes,Unknown,7122.0,3.0,26.0,15810.84,Mumbai,North,Puma Store C,Unknown,S,Cash,2023-11-30,1.0
2,3,4121,Jacket,Apparel,2464.0,1.0,29.0,1749.44,Mumbai,South,Puma Store B,Unknown,S,Card,2023-11-30,2.0
3,4,2920,Unknown,Accessories,912.0,4.0,26.0,2699.52,Hyderabad,North,Puma Store C,Unknown,S,Cash,NaT,3.0
5,6,3511,Jacket,Apparel,1107.0,1.0,13.0,963.09,Pune,South,Puma Store A,Store,S,UPI,2023-09-22,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,99995,3986,Sneakers,Footwear,5097.0,4.0,15.0,15902.64,Bangalore,North,Puma Store C,Online,L,Cash,2023-11-12,4.0
99996,99997,3208,Cap,Accessories,1616.0,1.0,15.0,1228.16,Mumbai,West,Puma Store C,Store,M,Card,2023-11-10,1.0
99997,99998,<NA>,Shorts,Apparel,4115.0,4.0,27.0,12015.80,Bangalore,North,Puma Store A,Online,M,UPI,2023-06-08,2.0
99998,99999,1047,Unknown,Footwear,7134.0,1.0,25.0,5350.50,Hyderabad,North,Puma Store B,Online,XL,UPI,2023-08-29,5.0
99999,100000,2716,T-shirt,Apparel,4683.0,2.0,6.0,8804.04,Pune,West,Puma Store C,Store,S,Card,2023-06-15,2.0

In [45]:
df.to_csv("puma_cleaned.csv", index=False)